Implemented Autonomous and ModuleManager (#17)
* Created the ModuleManager system

* Made ModuleManager final

* Changed ClassFormatError thrown by ModuleManager.getModule() to a NoSuchMethodError

* Added ModuleInitializer annotation

* Now ModuleManager just manually checks the class

* Added PlaneLauncher to ModuleManager

* Re-added thread start on init after global thread start

* Fixed ModuleManager.getModule() method signature

* removed DriveTrain.configureMotorDirections() assert statements (they don't work bc there is no known way to get the name)

* fixed IMU parameters in FieldCentricDriveTrain

* First half of RoadRunner tuning

* Skeleton autonomous OpModes

* Registered Auto Modules

* Improved Movement.hashCode()

* Removed Movement.Axis

* Removed Movement.magnitude()

* Changed ModuleManager.initModule() to use a SwitchStatement

* Deprecated unused modules

* Updated vulnerable dependency

* Fixed Autonomous impl build errors

* Removed nonexistent module

* Reorganized packages

* Fixed compile errors

* Moved test package into opmode package

* Added DriverMotorTest

* better telemetry for DriverMotorTest

* SwitchStatement is now more efficient

* DriveConstants.WHEEL_RADIUS is now a radius and not a diameter

* arm PID is now configurable again

* Revert "Updated vulnerable dependency"

This reverts commit 1774368c0005a80ecc77d2606afafc308880522b.

* SwitchStatement now uses a Hashtable instead of a list of Pairs

* Added javadoc to SwitchStatement

* Active intake tuning

* ConditionalHardwareDeviceGroup now inits with a hardware map

* Made PID tuner distance reasonable

* Actual tuning (up to DriveVelocityPID)

NOTE: The MAX_ACCEL & MAX_ANG_ACCEL are set to those values arbitrarily; no instruction was given on what value those should be yet

* ActiveIntake small warning fixes (style)

* Same tuning as before, but better (+Straight/Strafe Tests)

* Angle tuning

* Added telemetry.update() to ActiveIntakeTuner

* Active intake sets motor power on setPower

* Tuning

* Updated ActiveIntake

* ActiveIntake controls in TeleOpMain

* Added wrist presets to TeleOpMain

* Added HangModule

* Better HangModule skeleton

* Removed extra spaces

* Update ActiveIntake.java

The intake motor now runs with velocity PID