Added Module Manager (#14)
* Created the ModuleManager system

* Made ModuleManager final

* Changed ClassFormatError thrown by ModuleManager.getModule() to a NoSuchMethodError

* Added ModuleInitializer annotation

* Now ModuleManager just manually checks the class

* Added PlaneLauncher to ModuleManager

* Re-added thread start on init after global thread start

* Fixed ModuleManager.getModule() method signature

* removed DriveTrain.configureMotorDirections() assert statements (they don't work bc there is no known way to get the name)

* fixed IMU parameters in FieldCentricDriveTrain

* First half of RoadRunner tuning

* Skeleton autonomous OpModes

* Registered Auto Modules

* Improved Movement.hashCode()

* Removed Movement.Axis

* Removed Movement.magnitude()

* Changed ModuleManager.initModule() to use a SwitchStatement

* Deprecated unused modules

* Updated vulnerable dependency

* Fixed Autonomous impl build errors

* Removed nonexistent module

* Reorganized packages

* Fixed compile errors

* Moved test package into opmode package

* Added DriverMotorTest

* better telemetry for DriverMotorTest

* SwitchStatement is now more efficient